version: '3'
services:
  ch2:
    image: 'andrewcooke/choochoo:latest-local'
    container_name: 'choochoo'
    ports:
      - '127.0.0.1:8000:8000'
      - '127.0.0.1:8001:8001'
    environment:
      - 'CH2_DKR_URI=postgresql://postgres@postgresql/activity-0-34'
    volumes:
      - 'choochoo-data:/data'
    depends_on:
      - 'pg'
  pg:
    image: 'postgres:11.8-alpine'
    container_name: 'postgresql'
    shm_size: '1g'
    command: '-c config_file=/etc/postgresql/postgresql.conf'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
      - 'postgresql-log:/var/log'
      - './postgres.conf:/etc/postgresql/postgresql.conf'
volumes:
  choochoo-data:
    external: true
  postgresql-data:
    external: true
  postgresql-log:
    external: true
